# Digital Speech Processing
### Prof. Dr. Rodrigo Guido

### Student: Álvaro Leandro Cavalcante Carneiro

# Short Test Challenge
Working with audio convolutions

## Importing the necessary libraries

In [4]:
import numpy as np

## Defining signals
The first step is to define two arbitrary signals, in this case at least. I chose the same values seen in class to prove that the method is producing the right value.

In [25]:
signal = [1, 2, 3]
conv_filter = [4, 5]

### Ready to use convolution function
Numpy is an easy-to-use package with a lot of pre-defined functions used daily. One of them is convolution, which produces the same result that was calculated manually, as seen below.

In [19]:
numpy_conv = np.convolve(signal, conv_filter)
print(numpy_conv)

[ 4 13 22 15  0  0  0  0  0  0  0  0  0]


## Creating my own convolution function
For learning purposes, the idea is to create a simple function to produce the same result calculated manually and also by the numpy function, using my own script.

In [21]:
final_signal = []
iters = len(signal) + len(conv_filter)-1

signal = np.append(signal, ([0] * (iters - len(signal))))
conv_filter = np.append(conv_filter, ([0] * (iters - len(conv_filter))))

print(signal)
print(conv_filter)

[1 2 3 0]
[4 5 0 0]


In the code above, I first calculated the number of iterations that are needed to perform convolution in the array, in the *iters* variable. Then, it's necessary to fill the signal and the filter with zeros, to prevent out-of-index errors.

In [22]:
for j in range(iters):
    conv_sum = 0
    original_j = j
    while j >= 0:
        conv_sum += signal[j] * conv_filter[original_j - j]
        j -= 1

    final_signal.append(conv_sum)
print(final_signal)

[4, 13, 22, 15]


In the end, we loop through the array, multiplying the respectivelly values in each iteration. As seen, the obtained result is the same!

## Putting the code into one function
It's important to define the process above into a single function, to call it easily.

In [27]:
def get_convolved_value(signal, conv_filter):
    final_signal = []
    iters = len(signal) + len(conv_filter)-1

    signal = np.append(signal, ([0] * (iters - len(signal))))
    conv_filter = np.append(conv_filter, ([0] * (iters - len(conv_filter))))

    for j in range(iters):
        conv_sum = 0
        original_j = j
        while j >= 0:
            conv_sum += signal[j] * conv_filter[original_j - j]
            j -= 1

        final_signal.append(conv_sum)
    return final_signal

In [29]:
resulting_signal = get_convolved_value(signal, conv_filter)
resulting_signal

[4, 13, 22, 15]

## Convolving the signal itself
Let's convolve the signal with itself to see the results. First, using the numpy function and them using my created function!

In [31]:
np.convolve(resulting_signal, resulting_signal)

array([ 16, 104, 345, 692, 874, 660, 225])

In [32]:
get_convolved_value(resulting_signal, resulting_signal)

[16, 104, 345, 692, 874, 660, 225]

The values are the same, which shows that my function is correct!

## Finding the length of the result
The legth of the resulting array was already calculated in my custom convolution function, defined by the number of iteractions, once every new iteraction generates a new value!

- iters = len(signal) + len(conv_filter)-1

As shown, I get this value by the sum of the length of the filter and the signal minus 1.

In the first example, having 3 in the length of my signal and 2 in the filter, my resulting length is: (3+2) - 1 = 4.