# Digital Speech Processing
### Prof. Dr. Rodrigo Guido

### Student: Álvaro Leandro Cavalcante Carneiro

# Short Test 12
Resolve a order 3 LPC

## Importing the necessary libraries

In [1]:
import numpy as np 

## Defining parameters
The first step is to define the main parameters that will define the system, which are the order of the LPC and the initial signal. I also create a variable to store the x matrix and y array that will be used in the equation.

In [18]:
order = 3
signal = np.array([2,3,5,8,8,10,6])

x_matrix = np.array([])
y = np.array([])

## Getting equation
After that, I got the values that will be used in the equation. To get them, it's necessary to create a loop that will insert s values in the X array, where s is the LPC order. The y array is inserted based on s + 1. In the end, the x array is reshape to get a matrix shape.

In [19]:
for s in range(0, len(signal) - order):
    x_matrix = np.append(x_matrix, signal[s: s+order])
    y = np.append(y, signal[order+s])
    
x_matrix = x_matrix.reshape(len(signal)-order, order)

In [20]:
print('Matrix of values \n', x_matrix)
print('Y results \n', y)

Matrix of values 
 [[ 2.  3.  5.]
 [ 3.  5.  8.]
 [ 5.  8.  8.]
 [ 8.  8. 10.]]
Y results 
 [ 8.  8. 10.  6.]


## Applying the dot product
To turn this equation in a form that it's able to be solved, we multiply the matrix X and Y by the transpose of X.

In [21]:
x_result = np.dot(x_matrix.T, x_matrix)
y_result = np.dot(x_matrix.T, y)

print('X result \n', x_result)
print('Y result \n', y_result)

X result 
 [[102. 125. 154.]
 [125. 162. 199.]
 [154. 199. 253.]]
Y result 
 [138. 192. 244.]


## Getting the coefficients
To get the coefficients of the results, we can apply the linear algebra formula based on a numpy implementation. With this, we get the three coefficients (a1, a2 and a3) that were expected.

In [22]:
np.linalg.solve(x_result, y_result)

array([-1.91428198,  1.36756827,  1.05396577])