# Digital Speech Processing
### Prof. Dr. Rodrigo Guido

### Student: Álvaro Leandro Cavalcante Carneiro

# Short Test Challenge
Creating a band-stop filter.

## Importing the necessary libraries

In [42]:
import math
import numpy as np

## Defining filter parameters
First of all, it's important to define the necessary parameters, like the filter order, samples per second and cutoff frequency. In this case, we have frequency A and B to represent the cutpoints of our band-stop filter.

In [43]:
filter_order = 5
samples_second = 10000
cutoff_freq_a = 2500
cutoff_freq_b = 3500

## Function to get low pass filter
The function above gets the low pass filter. It also accepts a parameter to determine if the filter is a low pass to be transformed into a high pass, to change the division coefficient.

In [44]:
def get_low_pass_filter(filter_order, samples_second, cutoff_frequency, high_pass=False):
    frequency = samples_second / 2
    divisor = frequency / 1000
    dividend = cutoff_frequency / 1000 
    
    if high_pass:
        dividend = divisor - dividend

    final_filter = []

    for n in range(filter_order + 1):
        value = math.sin( ((dividend * math.pi) / divisor) * (n - (filter_order/2)) ) / (math.pi * (n - (filter_order/2)))
        final_filter.append(value)
    
    return np.array(final_filter)

Let's get the low pass filter, considering the first cutoff frequency.

In [45]:
low_pass_filter = get_low_pass_filter(filter_order, samples_second, cutoff_freq_a, False)
low_pass_filter

array([-0.09003163,  0.15005272,  0.45015816,  0.45015816,  0.15005272,
       -0.09003163])

After that, we call the same function, but this time passing the second cutoff frequency, and with the "high_pass" parameter set to True, to change the equation.

In [46]:
low_pass_b = get_low_pass_filter(filter_order, samples_second, cutoff_freq_b, True)
low_pass_b

array([0.09003163, 0.20959398, 0.28901933, 0.28901933, 0.20959398,
       0.09003163])

We'll use the same function created in the last short test to reverse the signal of our low pass filter, to achieve the high pass version! 

In [47]:
def get_high_pass_filter(filter_value):
    assert len(filter_value) % 2 == 0, "The filter len must be even"
       
    reversed_filter = np.array(filter_value)[::-1]
    inverse = []
    for i, value in enumerate(reversed_filter):
        if i % 2 != 0:
            inverse.append(-value)
        else:
            inverse.append(value)
    
    assert np.isclose(np.dot(filter_value, inverse), 0), "Not orthogonal filters"
    
    return np.array(inverse)

In [48]:
high_pass = get_high_pass_filter(low_pass_b)
high_pass

array([ 0.09003163, -0.20959398,  0.28901933, -0.28901933,  0.20959398,
       -0.09003163])

## Obtaining the band-stop filter
To get the band-stop filter, we just need to sum the coefficients of the low and high pass filters calculated previously. 

In [54]:
stop_band = low_pass_filter + high_pass
list(stop_band)

[1.3877787807814457e-17,
 -0.05954125616041256,
 0.7391774866797878,
 0.16113882947731828,
 0.35964669487944795,
 -0.18006326323142124]