# Digital Speech Processing
### Prof. Dr. Rodrigo Guido

### Student: Álvaro Leandro Cavalcante Carneiro

# Short Test 11
Applying AMDF to find fundamental frequency

## Importing the necessary libraries

In [6]:
import numpy as np

## Creating AMDF function

The first necessary step is to create a function that is able to calculate the absolute difference between two signals, as saw in the class. This is done by the *get_amdf* method.

In [3]:
def get_amdf(signal_a, signal_b):
    iters = len(signal_b)
    diffs = []

    for j in range(iters):
        diffs.append(abs(signal_b[j] - signal_a))

    for i in range(1, len(diffs)+1):
        right_zeros = len(diffs) - i
        left_zeros = i - 1
        
        if right_zeros > 0:
            diffs[i-1] = np.insert(diffs[i-1], 0, [0]*right_zeros)

        if left_zeros > 0:
            diffs[i-1] = np.insert(diffs[i-1], len(diffs[i-1]), [0]*left_zeros)

    return sum(diffs)

The function above just calculates the difference for each coefficient in relation to the other ones of the sign, and then, adds zeros in the beginning and end of the result to skip some values to be summed.

To validate the function, let's use the same signals that we saw in the class to check if we got the same results.

In [7]:
signal_a = [1,2,3]
signal_b = [4,5]
print(get_amdf(np.array(signal_a), np.array(signal_b)))

[4 6 4 1]


In [8]:
signal_a = [1,2,3]
signal_b = [1,2,3]
print(get_amdf(np.array(signal_a), np.array(signal_b)))

[2 2 0 2 2]


As saw, the values are the same. Let's use this function in the short test signal.

In [11]:
signal_a = [0, 1, 3, 0, 1, 3, 0, 1, 3, 0]
signal_b = [0, 1, 3, 0, 1, 3, 0, 1, 3, 0]
amdf_sig = get_amdf(np.array(signal_a), np.array(signal_b))
print(amdf_sig)

[ 0  4  6  0 10 12  0 16 18  0 18 16  0 12 10  0  6  4  0]


## Finding the period and F0

After that, we need to find the period (T) of the signal and the F0. The function *get_period* brings the first value for us, which is clearly 2 by looking at the signal.

In [26]:
def get_period(signal):
    minimum = min(signal)
    
    count = 0
    initial_p = None
    for s in signal:
        if s == minimum and initial_p is None:
            initial_p = count
            continue
        elif s == minimum and initial_p is not None:
            return count - initial_p
        count +=1

In [32]:
period = get_period(amdf_sig)
print('This signal has a period of', period, 'samples')

This signal has a period of 2 samples


However, this period is in a number of samples, and the correct form to capture this is in a time interval. Considering that this signal was sampled at 1.000 samples per second, we can infer the period of the signal based on this interval of 2 samples.

In [36]:
samples_per_second = 1000
period_in_seconds = period / samples_per_second
print('The signal has a period of', period_in_seconds, 'seconds')

The signal has a period of 0.002 seconds


Once we got the period in time, we can find the fundamental frequency (F0), given by the inverse of the period.

In [37]:
f0 = 1/period_in_seconds
print('The period of Pitch (F0) is', f0)

The period of Pitch (F0) is 500.0
